package com.myanalyzer.feedbackanalyzer;

import com.myanalyzer.feedbackanalyzer.user.Feedback;
import com.myanalyzer.feedbackanalyzer.user.FeedbackRepository;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.annotation.Rollback;

import java.util.List;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Rollback(false)
public class FeedbackRepositoryTests {

    @Autowired
    private FeedbackRepository repo;

    @Test
    public void testSaveFeedback() {
        // Create new Feedback without setting ID (Hibernate will generate it)
        Feedback feedback = new Feedback();
        feedback.setFeedback("This is an honest review which i made after i received the item, it is in very good condition and i am happy about it");

        // Save entity
        Feedback savedFb = repo.save(feedback);

        // Assertions
        Assertions.assertNotNull(savedFb);
        Assertions.assertNotNull(savedFb.getId(), "ID should be generated by Hibernate");
        Assertions.assertEquals(savedFb.getFeedback(), feedback.getFeedback());
    }

//    @Test
//    public void testUpdateFeedback() {
//        // First, fetch the existing feedback from DB
//        Feedback feedback = repo.findById(1).orElseThrow(() -> new RuntimeException("Feedback not found"));
//
//        // Update field
//        feedback.setFeedback("Updated feedback");
//
//        // Save updated entity
//        Feedback updatedFb = repo.save(feedback);
//
//        // Assertions
//        Assertions.assertEquals("Updated feedback", updatedFb.getFeedback());
//    }
//@Test
//public void testDisplayAllFeedbacks() {
//    // Fetch all feedbacks
//    List<Feedback> feedbackList = (List<Feedback>) repo.findAll();
//
//    // Display in console
//    feedbackList.forEach(feedback -> {
//        System.out.println("ID: " + feedback.getId());
//        System.out.println("Feedback: " + feedback.getFeedback());
//        System.out.println("---------------------------");
//    });
//}
}
